spring.application.name=recipe-manager
spring.datasource.url=jdbc:postgresql://localhost:5432/recipe_manager
spring.datasource.username=recipe_manager_backend_local
spring.datasource.password=12345678
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/recipe-manager
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/realms/recipe-manager/protocol/openid-connect/certs
